name: Branch Protection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  enforce-pr-workflow:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.head_commit.author.username != 'web-flow'
    steps:
      - name: Check if this is a direct push (not a PR merge)
        run: |
          # Check if this push came from a PR merge by looking at commit message
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MESSAGE" == *"Merge pull request"* ]] || [[ "$COMMIT_MESSAGE" == *"Co-authored-by:"* ]]; then
            echo "✅ This is a PR merge, allowing push to main"
            exit 0
          else
            echo "❌ Direct pushes to main branch are not allowed!"
            echo "Please create a pull request instead."
            echo "Commit message: $COMMIT_MESSAGE"
            exit 1
          fi

  pr-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          # Add test commands when test suite is implemented
          echo "✅ All checks passed"